# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0506dc4fc6ac1fa81d6e5820351348ee681ba6bf9da80c2b8e77bea8f4ef79890c20731a8060bf502efc447242e9fc9b26f82475dda24176a74ef353dcc56f1

test:
  secret_key_base: c889cea81994e7201c87eed5444d4f4ebea8c5bbd6494eee2ad4e04cd29fc7e22573ec8f6b6137d3965f261c8402bbe89b5c83bd29cbbb11eb5b53f68328380e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
